/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AcessoRapido: typeof import('./src/components/AcessoRapido.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Artigos: typeof import('./src/components/artigos.vue')['default']
    AssinaturaDigital: typeof import('./src/components/assinatura/AssinaturaDigital.vue')['default']
    Atuacao: typeof import('./src/components/atuacao.vue')['default']
    AuditoriaTimeline: typeof import('./src/components/auditoria/AuditoriaTimeline.vue')['default']
    BackupManager: typeof import('./src/components/backup/BackupManager.vue')['default']
    BoletimAluno: typeof import('./src/components/portal/BoletimAluno.vue')['default']
    CartaoPublicacao: typeof import('./src/components/portal/CartaoPublicacao.vue')['default']
    ContaForm: typeof import('./src/components/portal/ContaForm.vue')['default']
    Contatos: typeof import('./src/components/contatos.vue')['default']
    DashboardGeral: typeof import('./src/components/dashboard/DashboardGeral.vue')['default']
    EscolaSelector: typeof import('./src/components/escolas/EscolaSelector.vue')['default']
    EstadoConsulta: typeof import('./src/components/portal/EstadoConsulta.vue')['default']
    EstoqueForm: typeof import('./src/components/estoque/EstoqueForm.vue')['default']
    EstoqueList: typeof import('./src/components/estoque/EstoqueList.vue')['default']
    Foot: typeof import('./src/components/foot.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hero: typeof import('./src/components/hero.vue')['default']
    HistoricoEscola: typeof import('./src/components/estoque/HistoricoEscola.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    LeituraPagina: typeof import('./src/components/portal/LeituraPagina.vue')['default']
    LibrasPublica: typeof import('./src/components/portal/LibrasPublica.vue')['default']
    Local: typeof import('./src/components/local.vue')['default']
    MenuTelaInteira: typeof import('./src/components/portal/MenuTelaInteira.vue')['default']
    MovimentacaoForm: typeof import('./src/components/movimentacoes/MovimentacaoForm.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavHeader: typeof import('./src/components/NavHeader.vue')['default']
    NotificacoesAdmin: typeof import('./src/components/portal/NotificacoesAdmin.vue')['default']
    OneCalendario: typeof import('./src/components/OneCalendario.vue')['default']
    OneEdital: typeof import('./src/components/OneEdital.vue')['default']
    PortalFooter: typeof import('./src/components/portal/PortalFooter.vue')['default']
    Preloader: typeof import('./src/components/preloader.vue')['default']
    RecuperarPagina: typeof import('./src/components/portal/RecuperarPagina.vue')['default']
    ResumoRede: typeof import('./src/components/dashboard/ResumoRede.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Servicos: typeof import('./src/components/servicos.vue')['default']
    SessaoSegura: typeof import('./src/components/portal/SessaoSegura.vue')['default']
    SobreNos: typeof import('./src/components/SobreNos.vue')['default']
    SubNavHeader: typeof import('./src/components/SubNavHeader.vue')['default']
    VistoriaForm: typeof import('./src/components/vistoria/VistoriaForm.vue')['default']
  }
}
