export const SERVICOS = [
  {
    id: "matricula",
    titulo: "Matrícula escolar",
    resumo: "Orientações e solicitação de matrícula na rede municipal.",
    caminho: "/matricula",
    icone: "account-plus-outline",
    grupo: "Alunos e famílias",
  },
  {
    id: "calendario",
    titulo: "Calendário escolar",
    resumo: "Datas letivas, reuniões e eventos publicados pela Secretaria.",
    caminho: "/calendario",
    icone: "calendar-month-outline",
    grupo: "Alunos e famílias",
  },
  {
    id: "merenda",
    titulo: "Merenda escolar",
    resumo: "Escolas, cardápios mensais e vistorias concluídas.",
    caminho: "/merenda-escolar",
    icone: "food-apple-outline",
    grupo: "Alunos e famílias",
  },
  {
    id: "boletim",
    titulo: "Boletim e notas",
    resumo: "Consulta reservada às famílias e aos profissionais autorizados.",
    caminho: "/boletim",
    icone: "chart-line",
    grupo: "Alunos e famílias",
  },
  {
    id: "transporte",
    titulo: "Transporte escolar",
    resumo: "Rotas, horários e solicitação de atendimento.",
    caminho: "/transporte-escolar",
    icone: "bus-school",
    grupo: "Alunos e famílias",
  },
  {
    id: "biblioteca",
    titulo: "Biblioteca digital",
    resumo: "Livros, materiais e recursos educacionais publicados.",
    caminho: "/biblioteca-digital",
    icone: "book-open-page-variant-outline",
    grupo: "Comunidade",
  },
  {
    id: "editais",
    titulo: "Editais e concursos",
    resumo: "Publicações, prazos, documentos e resultados.",
    caminho: "/editais",
    icone: "file-document-outline",
    grupo: "Comunidade",
  },
  {
    id: "escolas",
    titulo: "Nossas escolas",
    resumo: "Conheça as unidades da rede e seus contatos públicos.",
    caminho: "/escolas",
    icone: "school-outline",
    grupo: "Comunidade",
  },
  {
    id: "transparencia",
    titulo: "Transparência",
    resumo: "Documentos e informações da gestão educacional.",
    caminho: "/transparencia",
    icone: "scale-balance",
    grupo: "Gestão pública",
  },
  {
    id: "contato",
    titulo: "Fale conosco",
    resumo: "Envie uma manifestação e acompanhe a resposta.",
    caminho: "/fale-conosco",
    icone: "message-text-outline",
    grupo: "Comunidade",
  },
];
export const PAGINAS = [
  [
    "institucional",
    "Institucional",
    "Conheça a Secretaria Municipal de Educação de Pedro II.",
  ],
  [
    "legislacao",
    "Legislação",
    "Normas e documentos publicados pela Secretaria.",
  ],
  [
    "planejamento",
    "Planejamento",
    "Planos, metas e instrumentos da gestão educacional.",
  ],
  [
    "transparencia",
    "Transparência",
    "Publicações e documentos da gestão da rede municipal.",
  ],
  [
    "indicadores",
    "Indicadores",
    "Indicadores publicados com período e fonte identificados.",
  ],
  ["sistemas", "Sistemas", "Acesse os sistemas e recursos da rede municipal."],
  [
    "acesso-a-informacao",
    "Acesso à informação",
    "Consulte informações públicas ou registre uma solicitação.",
  ],
  [
    "privacidade",
    "Privacidade",
    "Saiba quais informações são utilizadas nos serviços do portal.",
  ],
];
export const TIPOS_CONTEUDO = {
  noticia: "Notícia",
  pagina: "Página institucional",
  servico: "Carta de serviços",
  edital: "Edital / concurso",
  evento: "Calendário",
  documento: "Documento / transparência",
  biblioteca: "Biblioteca digital",
  transporte: "Rota de transporte",
  cardapio: "Cardápio mensal",
  indicador: "Indicador",
  sistema: "Sistema / link útil",
};
export const NAV = [
  { titulo: "Institucional", caminho: "/institucional" },
  { titulo: "Serviços", caminho: "/carta-de-servicos" },
  {
    titulo: "Rede escolar",
    filhos: [
      ["Escolas", "/escolas"],
      ["Calendário", "/calendario"],
      ["Merenda escolar", "/merenda-escolar"],
      ["Transporte", "/transporte-escolar"],
    ],
  },
  {
    titulo: "Publicações",
    filhos: [
      ["Notícias", "/noticias"],
      ["Editais", "/editais"],
      ["Biblioteca digital", "/biblioteca-digital"],
      ["Legislação", "/legislacao"],
      ["Sistemas", "/sistemas"],
    ],
  },
  {
    titulo: "Gestão pública",
    filhos: [
      ["Transparência", "/transparencia"],
      ["Planejamento", "/planejamento"],
      ["Indicadores", "/indicadores"],
      ["Acesso à informação", "/acesso-a-informacao"],
    ],
  },
  { titulo: "Fale conosco", caminho: "/fale-conosco" },
];
